---
- name: Manage users and groups
  hosts: localhost
  tasks:
    - name: Create group
      group:
        name: developers
        state: present
      tags: ["create_group"]

    - name: Create user
      user:
        name: john
        group: developers
        state: present
        shell: /bin/bash
        password: "{{ 'password' | password_hash('sha512') }}"
      tags: ["create_user"]

    - name: Remove user
      user:
        name: jane
        state: absent
      tags: ["remove_user"]

    - name: Add user to sudoers
      lineinfile:
        dest: /etc/sudoers
        line: "john ALL=(ALL) NOPASSWD:ALL"
        state: present
        validate: "visudo -cf %s"
      tags: ["add_user_to_sudoers"]
