---
- name: Complex Ansible playbook
  hosts: web_servers
  vars:
    web_servers:
      - server1
      - server2
    database_servers:
      - db1
      - db2

  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Copy Apache configuration file
      copy:
        src: apache.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart Apache

    - name: Ensure PHP is installed
      apt:
        name: php
        state: present

    - name: Configure PHP settings
      template:
        src: php.ini.j2
        dest: /etc/php.ini
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart Apache

    - name: Ensure MySQL is installed
      apt:
        name: mysql-server
        state: present
      when: "'db1' in database_servers"

    - name: Configure MySQL database
      template:
        src: my.cnf.j2
        dest: /etc/mysql/my.cnf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart MySQL
      when: "'db1' in database_servers"

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes
      when: "'server1' in web_servers"

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
      when: "'server2' in web_servers"

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
