---
- name: Example playbook with handlers
  hosts: web_servers
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
      notify:
        - Start Apache

    - name: Ensure Apache configuration file is present
      copy:
        src: apache.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart Apache

  handlers:
    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
